[package]
name = "mips"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]

[lib]
name = "mips"
path = "src/lib.rs"

[dependencies]
byteorder = "*"
rustc-serialize = "*"
docopt = "*"
docopt_macros = "*"
env_logger = "*"
log = "*"